language: perl
sudo: false
matrix:
  include:
    - perl: "5.20.1"
    - perl: "5.22"
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
install:
  - perl Makefile.PL && make && make test && make install && make clean
branches:
  except:
    - /^wip\//
    - /^blocked/
  only:
    - master
