language: perl
sudo: false
matrix:
  include:
    - perl: "5.20"
    - perl: "5.22"
    - perl: "5.16"
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  #- perl -V
  - cpanm --notest Inline::Module
  - cpanm --installdeps --showdeps --with-develop . | grep -v '^perl' | grep -v Configuring | grep -v 'Working'
  - cpanm -n `cpanm --installdeps --showdeps --with-develop . | grep -v '^perl' | grep -v Configuring | grep -v 'Working'`
#install:
#  - perl Makefile.PL && make && make test && make install && make clean
branches:
  except:
    - /^wip\//
    - /^blocked/
  only:
    - master
